# -*- coding: utf-8 -*-
"""
filled_comparison_filled.py
Generated by isp_plot_gui.py on 2026-03-10 08:28

Produces filled-band comparison charts for Gas technology.
One PDF per metric (Capacity, UF, Generation); one page per COMPARISON_SET.

Run from the project root (where ISP.db lives):
    python GUI/filled_comparison_filled.py

======================================================================
SQL — rows that feed the bands
======================================================================

    SELECT a.Id, a.Variable, a.Year, a.Value,
           v.Data_source, v.Scenario_1, v.Scenario_2,
           v.State, v.Region, v.Technology
    FROM data a
    INNER JOIN v_context_with_region v ON a.Id = v.Id
    WHERE a.Variable IN ('capacity', 'generation')
      -- Technology filter applied in Python after load:
      -- Technology IN ['Mid-merit Gas', 'Mid-merit Gas with CCS', 'Peaking Gas+Liquids', 'Flexible Gas', 'Flexible Gas with CCS']
      -- Each row below is one (ISP release, Scenario_1, CDP) combination
      -- that contributes to a band. The band spans min-to-max across all
      -- Scenario_1 values sharing the same ISP and CDP.
      AND (v.Data_source, v.Scenario_1, v.Scenario_2) IN (
          ('2022 Final ISP', 'Hydrogen Superpower - 2% discount rate', 'Counterfactual'),
          ('2022 Final ISP', 'Hydrogen Superpower - Offshore Wind', 'Counterfactual'),
          ('2022 Final ISP', 'Hydrogen Superpower - Updated Inputs', 'Counterfactual'),
          ('2022 Final ISP', 'Progressive Change - 2% discount rate', 'Counterfactual'),
          ('2022 Final ISP', 'Progressive Change - Offshore Wind', 'Counterfactual'),
          ('2022 Final ISP', 'Progressive Change - Updated Inputs', 'Counterfactual'),
          ('2022 Final ISP', 'Slow Change - 2% discount rate', 'Counterfactual'),
          ('2022 Final ISP', 'Slow Change - Offshore Wind', 'Counterfactual'),
          ('2022 Final ISP', 'Slow Change - Updated Inputs', 'Counterfactual'),
          ('2022 Final ISP', 'Step Change - 2% discount rate', 'Counterfactual'),
          ('2022 Final ISP', 'Step Change - Low Distributed Storage', 'Counterfactual'),
          ('2022 Final ISP', 'Step Change - Offshore Wind', 'Counterfactual'),
          ('2022 Final ISP', 'Step Change - Updated Inputs', 'Counterfactual'),
          ('2022 Final ISP', 'Strong Electrification Sensitivity - Updated Inputs', 'Counterfactual'),
          ('2024 Final ISP', 'Green Energy Exports - Core', 'Counterfactual'),
          ('2024 Final ISP', 'Green Energy Exports - Extended Eraring', 'Counterfactual'),
          ('2024 Final ISP', 'Progressive Change - Core', 'Counterfactual'),
          ('2024 Final ISP', 'Progressive Change - Extended Eraring', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Additional Load', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Alternative Worst Sequence', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Constrained Supply Chains', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Core', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Extended Eraring', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Low Hydrogen Flexibility', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Lower EV Uptake', 'Counterfactual'),
          ('2024 Final ISP', 'Step Change - Reduced CER Coordination', 'Counterfactual'),
          ('2026 Draft ISP', 'Accelerated Transition - Core', 'Counterfactual'),
          ('2026 Draft ISP', 'Slower Growth - Core', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Constrained Delivery', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Core', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Faster Coal Retirement', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Gas Development Projection Option 1', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Gas Development Projection Option 2', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Lower Energy Efficiency', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - No Further CER Coordination', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Slower Coal Retirement', 'Counterfactual'),
          ('2026 Draft ISP', 'Step Change - Under-investment Gas Development Projection', 'Counterfactual'),
      )
    ORDER BY v.Data_source, v.Scenario_1, v.Scenario_2, a.Year;

Notes:
  v_context_with_region fills NULL Region with synthetic state codes
  (N0, Q0, V0, S0, T0) for state-level ISP releases (2022 Final,
  2024 Draft). NEM totals are obtained by groupby without Region to
  avoid double-counting across storage levels.
======================================================================
"""

import sqlite3
import os
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


# ============================================================================
# CONFIGURE COMPARISON SETS — captured from GUI session 2026-03-10 08:28
# ============================================================================
# Each dict produces one page per output PDF.
# "scenarios": the Scenario_1 values whose min/max envelope forms the band.
# A single-item list collapses to a line.
# ============================================================================

COMPARISON_SETS = [
    {
        "title": 'All ODP scenarios — comparing ISP releases',
        "groups": [
            {
                "label":     '2022 Final ISP – all ODP scenarios',
                "colour":    '#E07B39',
                "alpha":     0.35,
                "isp":       '2022 Final ISP',
                "cdp":       'Counterfactual',
                "scenarios": [
                    'Hydrogen Superpower - 2% discount rate',
                    'Hydrogen Superpower - Offshore Wind',
                    'Hydrogen Superpower - Updated Inputs',
                    'Progressive Change - 2% discount rate',
                    'Progressive Change - Offshore Wind',
                    'Progressive Change - Updated Inputs',
                    'Slow Change - 2% discount rate',
                    'Slow Change - Offshore Wind',
                    'Slow Change - Updated Inputs',
                    'Step Change - 2% discount rate',
                    'Step Change - Low Distributed Storage',
                    'Step Change - Offshore Wind',
                    'Step Change - Updated Inputs',
                    'Strong Electrification Sensitivity - Updated Inputs',
                ],
            },
            {
                "label":     '2024 Final ISP – all ODP scenarios',
                "colour":    '#4C72B0',
                "alpha":     0.35,
                "isp":       '2024 Final ISP',
                "cdp":       'Counterfactual',
                "scenarios": [
                    'Green Energy Exports - Core',
                    'Green Energy Exports - Extended Eraring',
                    'Progressive Change - Core',
                    'Progressive Change - Extended Eraring',
                    'Step Change - Additional Load',
                    'Step Change - Alternative Worst Sequence',
                    'Step Change - Constrained Supply Chains',
                    'Step Change - Core',
                    'Step Change - Extended Eraring',
                    'Step Change - Low Hydrogen Flexibility',
                    'Step Change - Lower EV Uptake',
                    'Step Change - Reduced CER Coordination',
                ],
            },
            {
                "label":     '2026 Draft ISP – all ODP scenarios',
                "colour":    '#2CA02C',
                "alpha":     0.35,
                "isp":       '2026 Draft ISP',
                "cdp":       'Counterfactual',
                "scenarios": [
                    'Accelerated Transition - Core',
                    'Slower Growth - Core',
                    'Step Change - Constrained Delivery',
                    'Step Change - Core',
                    'Step Change - Faster Coal Retirement',
                    'Step Change - Gas Development Projection Option 1',
                    'Step Change - Gas Development Projection Option 2',
                    'Step Change - Lower Energy Efficiency',
                    'Step Change - No Further CER Coordination',
                    'Step Change - Slower Coal Retirement',
                    'Step Change - Under-investment Gas Development Projection',
                ],
            },
        ],
    },
]

MAX_CAPACITY   = 26
MAX_UF         = 100
MAX_GENERATION = 140000

TECH_FILTER = ['Mid-merit Gas', 'Mid-merit Gas with CCS', 'Peaking Gas+Liquids', 'Flexible Gas', 'Flexible Gas with CCS']


# ============================================================================
# DATA LOADING
# ============================================================================

def get_data():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ISP.db")
    conn    = sqlite3.connect(db_path)
    cap = pd.read_sql(
        """SELECT a.Id, a.Variable, a.Year, a.Value,
                  v.Data_source, v.Scenario_1, v.Scenario_2,
                  v.State, v.Region, v.Technology
           FROM data a
           INNER JOIN v_context_with_region v ON a.Id = v.Id
           WHERE a.Variable = 'capacity'""", conn)
    gen = pd.read_sql(
        """SELECT a.Id, a.Variable, a.Year, a.Value,
                  v.Data_source, v.Scenario_1, v.Scenario_2,
                  v.State, v.Region, v.Technology
           FROM data a
           INNER JOIN v_context_with_region v ON a.Id = v.Id
           WHERE a.Variable = 'generation'""", conn)
    conn.close()
    for df in (cap, gen):
        df.drop(df[df.Year.isin(["Existing and Committed", "Un33"])].index, inplace=True)
        df.dropna(subset=["Value", "Scenario_2"], inplace=True)
        df["Year"] = df["Year"].astype(int)
    cap["Value"] = cap["Value"].astype(float) / 1000
    gen["Value"] = gen["Value"].astype(float)
    return cap, gen


# ============================================================================
# AGGREGATION
# ============================================================================

print("Loading data from ISP.db...")
cap_raw, gen_raw = get_data()

cap = cap_raw[cap_raw.Technology.isin(TECH_FILTER)].copy()
gen = gen_raw[gen_raw.Technology.isin(TECH_FILTER)].copy()
cap["max_annual_gen"] = cap["Value"] * 24 * 365

grp = ["Data_source", "Scenario_1", "Scenario_2", "Year"]
gpg_cap_sum = cap.groupby(grp, as_index=False).agg({"Value": "sum", "max_annual_gen": "sum"})
gpg_gen_sum = gen.groupby(grp, as_index=False)["Value"].sum()
gpg_uf      = (
    gpg_cap_sum[grp + ["max_annual_gen"]]
    .merge(gpg_gen_sum, on=grp, how="inner")
)
gpg_uf["Value"] = gpg_uf["Value"] / gpg_uf["max_annual_gen"] * 100

print(f"Data loaded. Rendering {len(COMPARISON_SETS)} comparison set(s) x 3 metrics...\n")


# ============================================================================
# PLOT FUNCTIONS
# ============================================================================

def build_band(df_metric, isp, cdp, scenarios):
    pieces = []
    for scen in scenarios:
        sub = df_metric[
            (df_metric["Data_source"] == isp) &
            (df_metric["Scenario_1"]  == scen) &
            (df_metric["Scenario_2"]  == cdp)
        ][["Year", "Value"]].set_index("Year").rename(columns={"Value": scen})
        if not sub.empty:
            pieces.append(sub)
    if not pieces:
        return None, None
    wide = pd.concat(pieces, axis=1).sort_index()
    return wide.min(axis=1), wide.max(axis=1)


def plot_comparison_page(df_metric, comparison_set, ylabel, max_value):
    fig, ax = plt.subplots(figsize=(13, 8))
    for group in comparison_set["groups"]:
        env_min, env_max = build_band(
            df_metric, group["isp"], group["cdp"], group["scenarios"])
        if env_min is None:
            print(f"  WARNING: no data for '{group['label']}' "
                  f"(ISP={group['isp']}, CDP={group['cdp']})")
            continue
        ax.fill_between(env_min.index, env_min, env_max,
                        alpha=group["alpha"], color=group["colour"],
                        label=group["label"], linewidth=0)
    ax.set_title(comparison_set["title"], fontweight="bold", fontsize=15)
    ax.set_ylabel(ylabel, fontweight="bold", fontsize=13)
    ax.set_ylim(0, max_value)
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend(loc="best", fontsize=11, framealpha=0.9)
    plt.tight_layout()
    return fig


# ============================================================================
# RENDER
# ============================================================================

METRICS = [
    {"name": "Capacity",   "df": "gpg_cap_sum", "ylabel": "Capacity [GW]",        "max_value": 26, "outfile": "filled_comparison_Capacity.pdf"},
    {"name": "UF",         "df": "gpg_uf",      "ylabel": "UF [GWh / GWh x 100]", "max_value": 100,  "outfile": "filled_comparison_UF.pdf"},
    {"name": "Generation", "df": "gpg_gen_sum", "ylabel": "Generation [GWh]",      "max_value": 140000, "outfile": "filled_comparison_Generation.pdf"},
]

for metric in METRICS:
    with PdfPages(metric["outfile"]) as pdf:
        for cset in COMPARISON_SETS:
            page_cset = {**cset, "title": f"{metric['name']}: {cset['title']}"}
            fig = plot_comparison_page(
                df_metric      = locals()[metric["df"]],
                comparison_set = page_cset,
                ylabel         = metric["ylabel"],
                max_value      = metric["max_value"],
            )
            pdf.savefig(fig)
            plt.close(fig)
            print(f"  [{metric['name']}] {cset['title']}")
    print(f"Saved: {metric['outfile']}\n")

print("Done.")
