# -*- coding: utf-8 -*-
"""
isp_line_plots_isp_plots.py
Generated by isp_plot_gui.py on 2026-03-10 13:12

Reproduces Core / Sensitivity line plots for Gas.
Run from the project root (where ISP.db lives):
    python GUI/isp_line_plots_isp_plots.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SQL — rows that feed these plots
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    SELECT a.Id, a.Variable, a.Year, a.Value,
           v.Data_source, v.Scenario_1, v.Scenario_2,
           v.State, v.Region, v.Technology
    FROM data a
    INNER JOIN v_context_with_region v ON a.Id = v.Id
    WHERE a.Variable IN ('capacity', 'generation')
      -- Technology filter (applied in Python):
      -- Technology IN ['Mid-merit Gas', 'Mid-merit Gas with CCS', 'Peaking Gas+Liquids', 'Flexible Gas', 'Flexible Gas with CCS']
      -- Scenario / CDP filter (ODP rows only):
      AND (v.Data_source, v.Scenario_1, v.Scenario_2) IN (
          ('2022 Draft ISP', 'Hydrogen Superpower - 10% discount rate', 'CDP11'),
          ('2022 Final ISP', 'Slow Change - Offshore Wind', 'CDP10'),
          ('2026 Draft ISP', 'Accelerated Transition - Core', 'CDP4 (ODP)'),
          ('2022 Draft ISP', 'Hydrogen Superpower - 10% discount rate', 'CDP1'),
      )
    ORDER BY v.Data_source, v.Scenario_1, v.Scenario_2, a.Year;

Notes:
  v_context_with_region fills NULL Region with synthetic state codes
  (N0, Q0, V0, S0, T0) for state-level ISP releases (2022 Final,
  2024 Draft). NEM totals are obtained by groupby without Region to
  avoid double-counting across storage levels.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

import sqlite3, os
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


# ============================================================================
# CONFIGURATION — edit here to change what is plotted
# ============================================================================

core_scenarios = pd.DataFrame([
    {"ISP": '2022 Draft ISP', "core": 'Hydrogen Superpower - 10% discount rate', "ODP": 'CDP11', "colour": '#000000', "linestyle": '-'},
    {"ISP": '2022 Final ISP', "core": 'Slow Change - Offshore Wind', "ODP": 'CDP10', "colour": '#E07B39', "linestyle": '-'},
    {"ISP": '2026 Draft ISP', "core": 'Accelerated Transition - Core', "ODP": 'CDP4 (ODP)', "colour": '#4C72B0', "linestyle": '-'},
    {"ISP": '2022 Draft ISP', "core": 'Hydrogen Superpower - 10% discount rate', "ODP": 'CDP1', "colour": '#2CA02C', "linestyle": '-'},
])

odp = pd.DataFrame([
    {"Data_source": '2022 Draft ISP', "Scenario_2": 'CDP11'},
    {"Data_source": '2022 Final ISP', "Scenario_2": 'CDP10'},
    {"Data_source": '2026 Draft ISP', "Scenario_2": 'CDP4 (ODP)'},
    {"Data_source": '2022 Draft ISP', "Scenario_2": 'CDP1'},
])

reference_scenarios = pd.DataFrame([
    {"ISP": '2022 Draft ISP', "core": 'Hydrogen Superpower - 10% discount rate'},
])

TECH_FILTER    = ['Mid-merit Gas', 'Mid-merit Gas with CCS', 'Peaking Gas+Liquids', 'Flexible Gas', 'Flexible Gas with CCS']
HIGHLIGHT_ISP  = '2022 Draft ISP'
HIGHLIGHT_CORE = 'Hydrogen Superpower - 10% discount rate'

# (dataframe_key, ylabel, title_label, y_max)
METRICS = [
    ("capacity_sum",   "Capacity [GW]",         "Capacity",   26),
    ("util_factor",    "UF [GWh / GWh x 100]",  "UF",         100),
    ("generation_sum", "Generation [GWh]",       "Generation", 140000),
]

DO_CORE_PLOT   = True
DO_SENS_PLOT   = True

OUTPUT_PDF = 'isp_line_plots.pdf'


# ============================================================================
# DATA LOADING
# ============================================================================

def get_data():
    db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "ISP.db")
    conn    = sqlite3.connect(db_path)
    cap = pd.read_sql(
        """SELECT a.Id, a.Variable, a.Year, a.Value,
                  v.Data_source, v.Scenario_1, v.Scenario_2,
                  v.State, v.Region, v.Technology
           FROM data a
           INNER JOIN v_context_with_region v ON a.Id = v.Id
           WHERE a.Variable = 'capacity'""", conn)
    gen = pd.read_sql(
        """SELECT a.Id, a.Variable, a.Year, a.Value,
                  v.Data_source, v.Scenario_1, v.Scenario_2,
                  v.State, v.Region, v.Technology
           FROM data a
           INNER JOIN v_context_with_region v ON a.Id = v.Id
           WHERE a.Variable = 'generation'""", conn)
    ctx = pd.read_sql("SELECT * FROM v_context_with_region", conn)
    conn.close()
    for df in (cap, gen):
        df.drop(df[df.Year.isin(["Existing and Committed", "Un33"])].index, inplace=True)
        df.dropna(subset=["Value", "Scenario_2"], inplace=True)
        df["Year"] = df["Year"].astype(int)
    cap["Value"] = cap["Value"].astype(float) / 1000
    gen["Value"] = gen["Value"].astype(float)
    return cap, gen, ctx


# ============================================================================
# AGGREGATION
# ============================================================================

print("Loading data...")
cap_raw, gen_raw, context = get_data()

cap = cap_raw[cap_raw.Technology.isin(TECH_FILTER)].copy()
gen = gen_raw[gen_raw.Technology.isin(TECH_FILTER)].copy()
cap["max_annual_gen"] = cap["Value"] * 24 * 365

grp = ["Data_source", "Scenario_1", "Scenario_2", "Year"]
capacity_sum   = cap.groupby(grp, as_index=False).agg({"Value": "sum", "max_annual_gen": "sum"})
generation_sum = gen.groupby(grp, as_index=False)["Value"].sum()
util_factor    = capacity_sum[grp + ["max_annual_gen"]].merge(generation_sum, on=grp, how="inner")
util_factor["Value"] = util_factor["Value"] / util_factor["max_annual_gen"] * 100

all_scenarios     = context[["Data_source","Scenario_1","Scenario_2"]].drop_duplicates().dropna().reset_index(drop=True)
all_scenarios_odp = all_scenarios.merge(odp, how="inner")

DATA = {"capacity_sum": capacity_sum, "util_factor": util_factor, "generation_sum": generation_sum}
print("Data loaded.")


# ============================================================================
# PLOT FUNCTIONS
# ============================================================================

def plot_core(df, ylabel, title, ymax):
    fig, ax = plt.subplots(figsize=(12, 8))
    for _, row in core_scenarios.iterrows():
        sub    = df[(df.Data_source==row["ISP"]) & (df.Scenario_1==row["core"]) & (df.Scenario_2==row["ODP"])]
        is_ref = (row["ISP"]==HIGHLIGHT_ISP and row["core"]==HIGHLIGHT_CORE)
        ax.plot(sub.Year, sub.Value,
                color     = "black" if is_ref else row["colour"],
                linestyle = "-" if is_ref else row["linestyle"],
                linewidth = 3.5 if is_ref else 1.5,
                label     = f"{row['ISP']} – {row['core']}" + (" ★" if is_ref else ""))
    ax.set_title(f"Core Scenarios – {title}", fontweight="bold", fontsize=16)
    ax.set_ylabel(ylabel, fontweight="bold", fontsize=14)
    ax.set_ylim(0, ymax); ax.legend(loc="best", fontsize=11); ax.grid()
    plt.tight_layout()
    return fig


def plot_sensitivity(df, ylabel, title, ymax, pdf):
    for isp in core_scenarios["ISP"].unique():
        isp_data   = all_scenarios_odp[all_scenarios_odp.Data_source==isp].copy()
        ref_match  = reference_scenarios[reference_scenarios.ISP==isp]
        highlight  = ref_match["core"].iloc[0] if not ref_match.empty else ""
        core_names = core_scenarios[core_scenarios.ISP==isp]["core"].values
        fig, ax    = plt.subplots(figsize=(12, 8))
        for _, row in isp_data.iterrows():
            sub  = df[(df.Data_source==isp) & (df.Scenario_1==row.Scenario_1) & (df.Scenario_2==row.Scenario_2)]
            ref  = (row.Scenario_1==highlight)
            core = (row.Scenario_1 in core_names)
            ax.plot(sub.Year, sub.Value,
                    color="black" if ref else _color(row.Scenario_1),
                    linestyle="-" if (ref or core) else "--",
                    linewidth=3.5 if ref else 1.5,
                    label=f"{row.Scenario_1} – {row.Scenario_2}")
        ax.set_title(f"{title} ODP – core & sensitivity: {isp}", fontweight="bold", fontsize=16)
        ax.set_ylabel(ylabel, fontweight="bold", fontsize=14)
        ax.set_ylim(0, ymax); ax.legend(loc="best", fontsize=10); ax.grid()
        plt.tight_layout(); pdf.savefig(fig); plt.close(fig)


# ============================================================================
# RENDER
# ============================================================================

with PdfPages(OUTPUT_PDF) as pdf:
    for df_key, ylabel, title, ymax in METRICS:
        df = DATA[df_key]
        if DO_CORE_PLOT:
            fig = plot_core(df, ylabel, title, ymax)
            pdf.savefig(fig); plt.close(fig)
            print(f"  [Core] {title}")
        if DO_SENS_PLOT:
            plot_sensitivity(df, ylabel, title, ymax, pdf)
            print(f"  [Sensitivity] {title}")

print(f"Saved: {OUTPUT_PDF}")
